// AUTOGENERATED FILE - LocalisationEditor.GenerateLocalisationConfig

using UnityEngine;

// Namespace limited to tests
namespace DUCK.Localisation.Tests
{
	public class TestKeys
	{
		public enum Test
		{
			Hello = -1645422315,
			ThankYou = 1473857970,
			Goodbye = -1301568364
		}
	}

	public class TestLoc
	{
		// Autogenerated code: please make changes to the template file and re-generate
		public static string Get(object key)
		{
			var target = string.Empty;
			try
			{
				var success = Get((int)key, out target);

				if (!success)
				{
					Debug.LogError(string.Format("Localisation value not found: {0}", key));
				}
			}
			catch (System.InvalidCastException e)
			{
				Debug.LogError(string.Format("Localisation key could not be cast to int: {0}", key) + $"\n{e.Message}");
			}

			return target;
		}

		// Autogenerated code: please make changes to the template file and re-generate
		public static bool Get(int key, out string target)
		{
			if (!Localiser.GetLocalisedString(key, out target))
			{
				target = string.Empty;
				return false;
			}

			return true;
		}
	}
}